### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by AndersRehcam** [iRB-Lab/py-ga-VRPTW#5]
First of all thanks for your great code! It's very well written and documented.

I plotted the fitness values (min, max: blue; avg: green) for the solution process of the provided R101 example. I am wondering, if the algorithm performs well, because the max value doesn't increase and even dicreases after a view generations. 

![screenshot-gacvrptw](https://user-images.githubusercontent.com/34001537/36355382-ae021824-14e2-11e8-83f2-d6f35d13a13f.png)

I'm not sure, if I'm right, but in my point of view that means that the best individual is already being created with the initialization of the problem. Furthermore the optimal solution (max) seems to be getting worser during the solution procedure. I guess it should be the other way round, so that the optimal solution (max value) gets better over time. I observed this behavior for other examples, too.

Do you have an idea what the problem could be here? Maybe something with the operators? Or am I totally wrong with my understanding of the plot?

Thanks a lot for your support!

**Comment by iROCKBUNNY** [comment]
@AndersRehcam Hi, there! You are right. The performances of the given examples are poor. The results are not yet converged. 

The parameters of the GA have to be tuned to get the best results. You may try various combinations of different chromosome representation methods and GA operators as well as parameters, in order to tune a final well-converged approach. You may also implement your own functions of the chromosome encoding/decoding, evaluation, selection, crossover and mutation, instead of using those given in this project to achieve better performances.

**Comment by AndersRehcam** [comment]
Thanks for your fast reply! Allright, I think I will start with some different crossover operators at first. Thanks for your help!

**Comment by iROCKBUNNY** [comment]
@AndersRehcam I suggest you to start with some novel ways of chromosome encoding. That can be more efficient.
